# Schema for the configuration files of the captcha module.
#captcha_wrong_response_counter

captcha.settings:
  type: mapping
  label: 'External Links Settings'
  mapping:
    captcha_default_challenge:
      type: string
      label: 'The default challenge for captcha.'
    captcha_description:
      type: string
      label: 'The default captcha description.'
    captcha_administration_mode:
      type: boolean
      label: 'Add CAPTCHA administration links to forms'
    captcha_allow_on_admin_pages:
      type: boolean
      label: 'Allow CAPTCHAs and CAPTCHA administration links on administrative pages'
    captcha_add_captcha_description:
      type: boolean
      label: 'Add a description to the CAPTCHA'
    captcha_default_validation:
      type: integer
      label: 'Default CAPTCHA validation'
    captcha_persistence:
      type: integer
      label: 'CAPTCHA Persistence'
    captcha_enable_stats:
      type: boolean
      label: 'Enable statistics'
    captcha_log_wrong_responses:
      type: boolean
      label: 'Log wrong responses'